server:
  port: 7070

spring:
  profiles:
    active: prod

---
server:
  port: 7071
spring:
  config:
    activate:
      on-profile: dev

---
server:
  port: 7072
spring:
  config:
    activate:
      on-profile: test

---
server:
  port: 7073
spring:
  config:
    activate:
      on-profile: prod

