server:
  port: 8080

# redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0